#!/usr/bin/env zsh

local original=${1:?two dbs}; shift
local import=${1:?two dbs}; shift

# for reasons I cannot use the encryption filter here.
# most annoying.

sqlite3 "${original}" <<EOF
ATTACH DATABASE '${import}' AS o;

-- copy missing commands and places
INSERT INTO commands (argv) SELECT argv FROM o.commands;
INSERT INTO places (host, dir) SELECT host, dir FROM o.places;

-- insert missing history, rewriting IDs
-- could uniquify sessions by host in this way too

INSERT INTO history (session, command_id, place_id, exit_status, start_time, duration)
SELECT HO.session, C.id, P.id, HO.exit_status, HO.start_time, HO.duration
FROM o.history HO
LEFT JOIN o.places PO ON HO.place_id = PO.id
LEFT JOIN o.commands CO ON HO.command_id = CO.id
LEFT JOIN commands C ON C.argv = CO.argv
LEFT JOIN places P ON (P.host = PO.host
AND P.dir = PO.dir)
;
EOF
